// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PassCodeServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PassCodeServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<bool> VerifyPassword(string passCodeID, string inputPassword)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "SAIGOutsideSAIGCloud",
                "VerifyPassword",
                new Dictionary<string, object>()
                {
                    {"passCodeID", passCodeID},
                    {"inputPassword", inputPassword},
                });
        }

        public async Task<bool> VerifyPasswordAndSolveScene(string passCodeID, string inputPassword, string sceneID)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "SAIGOutsideSAIGCloud",
                "VerifyPasswordAndSolveScene",
                new Dictionary<string, object>()
                {
                    {"passCodeID", passCodeID},
                    {"inputPassword", inputPassword},
                    {"sceneID", sceneID},
                });
        }
    }
}
